version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '3306:3306' 
    volumes:
      - ./db/data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

###> phpfpm ###
  php:
    container_name: php
    build:
      context: ./php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=8.0
    volumes:
      - ../app:/var/www  
    ports:
      - '9000:9000'
##< phpfpm ###

###> nginx ###
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
##< nginx ###
